# Generated by Django 5.1.6 on 2025-03-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_order_status_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Cash'), (2, 'Card')], null=True),
        ),
    ]
