# Generated by Django 5.1.6 on 2025-03-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
